modLoader="javafml"
loaderVersion="[34,)"
license="GNU GPLv3"
[[mods]]
modId="editmobdrops"
version="1.3.2"
displayName="Edit Mob Drops"
authors="Powerthegreat"
description='''A mod for editing mob drops.'''