modLoader="javafml"
loaderVersion="[43,)"
license="GNU GPLv3"
[[mods]]
modId="editmobdrops"
version="${file.jarVersion}"
displayName="Edit Mob Drops"
authors="Powerthegreat"
description='''A mod for editing mob drops.'''